# MyData
title: ğŸŒˆ ì„±ì¥í•˜ëŠ” ê°œë°œìì˜ ê¸°ë¡s
email: icho0405@gmail.com
description: ê¸ì •ì ì¸ ìƒê°ì´ ê¸ì •ì ì¸ í™˜ê²½ì„ ë§Œë“ ë‹¤ë¼ëŠ” ë§ì„ ì¢‹ì•„í•©ë‹ˆë‹¤. ì‚¬ìš©ì ê´€ì ì—ì„œ ê°œë°œí•˜ëŠ” í”„ë¡ íŠ¸ì—”ë“œ ì—”ì§€ë‹ˆì–´ì…ë‹ˆë‹¤. ìƒˆë¡œìš´ ë¬´ì–¸ê°€ë¥¼ ë°°ìš°ëŠ” ê²ƒì„ ì¦ê¹ë‹ˆë‹¤.
url: "https://yurim45.github.io"
baseurl: /
github_username: yurim45

# favicon: assets/built/images/favicon.jpg
# faviconìœ¼ë¡œ ì‚¬ìš©í•  image

# cover: assets/built/images/blog-cover1.png
# blog homeì— í‘œì‹œë  blog cover image.

exclude:
  - _post/cs
  - _post/study
  - _post/projects
  - _post/about

# Build settings
theme: minima
plugins:
  - jekyll-feed
paginate: 5 # ì²« í˜ì´ì§€ì—ë³´ì—¬ì¤„ ìµœê·¼ ê²Œì‹œë¬¼ ìˆ˜ë¥¼ ì§€ì •
paginate_path: /page:num/
# Disqus
# disqus: True
# disqus_shortname:
# disqusëŠ” ì˜¨ë¼ì¸ ëŒ“ê¸€ ì‹œìŠ¤í…œ. ëŒ“ê¸€ ê¸°ëŠ¥ì„ ì‚¬ìš©í•˜ê¸° ìœ„í•´
# disqusë¥¼ ì´ìš©í•  ê²ƒì¸ì§€ ì—¬ë¶€ì™€ ë§Œì•½ ì‚¬ìš©í•˜ë©´
# disqus shortnameì„ ì…ë ¥ ( disqus usernameì´ ì•„ë‹˜ )
