# MyData
title: 성장하는 개발자의 개발일기
email: icho0405@gmail.com
description: 긍정적인 생각이 긍정적인 환경을 만든다라는 말을 좋아합니다. 사용자 관점에서 개발하는 프론트엔드 엔지니어입니다. 새로운 무언가를 배우는 것을 즐깁니다.
url: "https://yurim45.github.io"
baseurl: /
github_username: yurim45

favicon: assets/built/images/favicon.jpg
# favicon으로 사용할 image

# cover: assets/built/images/blog-cover1.png
# blog home에 표시될 blog cover image.

# Build settings
theme: minima
plugins:
  - jekyll-feed
paginate: 20
# Disqus
# disqus: True
# disqus_shortname:
# disqus는 온라인 댓글 시스템. 댓글 기능을 사용하기 위해
# disqus를 이용할 것인지 여부와 만약 사용하면
# disqus shortname을 입력 ( disqus username이 아님 )
